### ISSUE TITLE
Unable to run OS X binaries. 

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/memgator#1]
When I double click either of the Darwin binaries in OS X, I get a text file displaying the contents of the file. They don't appear to run natively. Should they?
![screen shot 2015-09-08 at 7 01 43 am](https://cloud.githubusercontent.com/assets/2514780/9733247/b01a5114-55f7-11e5-9e5a-245cee1772f2.png)
![screen shot 2015-09-08 at 7 01 46 am](https://cloud.githubusercontent.com/assets/2514780/9733248/b01b2238-55f7-11e5-8075-f8f6b71b7768.png)

**Comment by ibnesayeed** [comment]
Can you run them from the CLI/terminal?

**Comment by ibnesayeed** [comment]
Oops, there was an issue in the cross-compilation. I have fixed it and updated the binaries. Please grab the new binary and try it again.

**Comment by machawk1** [comment]
All is working now. Once I change the permissions to be executable, double clicking on the binary launches the terminal showing usage.
