### ISSUE TITLE
Version in response payload is inaccurate

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/memgator#103]
We have a version of memgator deployed at `memgator.cs.odu.edu` where the response payload does not align with the version reported in the response headers. 

`curl -i memgator.cs.odu.edu` has the following output. Note the two versions reported 1.0rc-7 in the headers and 1.0rc-5 in the payload.

```html
HTTP/1.1 200 OK
Server: nginx/1.11.3
Date: Tue, 27 Jun 2017 22:12:27 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 859
Connection: keep-alive
Accept-Ranges: bytes
Last-Modified: Sat, 04 Jun 2016 18:35:50 GMT
X-Generator: MemGator:1.0-rc7

<!DOCTYPE html>
<html lang="en">
<head>
<title>MemGator | A Memento Aggregator</title>
</head>
<body>
<pre>
<a href="https://github.com/oduwsdl/memgator">MemGator</a> 1.0-rc5
   _____                  _______       __
  /     \  _____  _____  / _____/______/  |___________
 /  Y Y  \/  __ \/     \/  \  ___\__  \   _/ _ \_   _ \
/   | |   \  ___/  Y Y  \   \_\  \/ __ |  | |_| |  | \/
\__/___\__/\____\__|_|__/\_______/_____|__|\___/|__|

TimeMap   : http://memgator.cs.odu.edu/timemap/{FORMAT}/{URI-R}
TimeGate  : http://memgator.cs.odu.edu/timegate/{URI-R} [Accept-Datetime]
Memento   : http://memgator.cs.odu.edu/memento[/{FORMAT}]/{DATETIME}/{URI-R}
Benchmark : http://memgator.cs.odu.edu/monitor [SSE]

# FORMAT          => link|json|cdxj
# DATETIME        => YYYY[MM[DD[hh[mm[ss]]]]]
# Accept-Datetime => Header in RFC1123 format
</pre>
</body>
</html>
```

**Comment by ibnesayeed** [comment]
It was not a MemGator bug, instead the issue was in the plain static file we serve at the root of the domain in our deployment which is not associated with the repo. I have modified that file on our server and it is all good now.

**Comment by machawk1** [comment]
@ibnesayeed Is there any way to sync up the version reported in the header and payload?

**Comment by ibnesayeed** [comment]
That file will eventually be replaced with our fancier interfaces, so I won't worry too much about that. Again, that is a deployment specific thing that has nothing to do with this repo. We can actually put some unicorns and/or zombies there if we like. :-)

**Comment by machawk1** [comment]
@ibnesayeed Looking forward to the fancier interface. I'll continue to worry until then. 🦄
