### ISSUE TITLE
Error after MemGator's `go get ...` command

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/memgator#12]
I have setup my go environment then `cd $GOPATH`, which puts me at `/Users/MYUSERNAME/go`. I then run `go get github.com/oduwsdl/memgator` and receive the error:

```sh
# github.com/oduwsdl/memgator
src/github.com/oduwsdl/memgator/main.go:128: unknown http.Client field 'Timeout' in struct literal
```

MacOS X 10.10.5. go version go1.2.2 darwin/amd64. Occurs with no subdirectories within

**Comment by ibnesayeed** [comment]
Please try upgrading your Go to the latest version. The `Client.Timeout` requires at least Go 1.3. According to the [Go 1.3 Release Notes](https://golang.org/doc/go1.3):

> The net/http package's HTTP client now has an optional Client.Timeout field to specify an end-to-end timeout on requests made using the client.

**Comment by machawk1** [comment]
I upgraded go:

```sh
$ go version
go version go1.5.1 darwin/amd64
```
then:
```sh
$ cd $GOPATH
$ go get github.com/oduwsdl/memgator
```
returns
```sh
# github.com/oduwsdl/memgator
src/github.com/oduwsdl/memgator/main.go:7: import /Users/MYUSERNAME/go/pkg/darwin_amd64/github.com/oduwsdl/memgator/pkg/mflag.a: object is [darwin amd64 go1.2.2 X:none] expected [darwin amd64 go1.5.1 X:none]
```

**Comment by machawk1** [comment]
Scratch that. I cleared everything in the $GOPATH, reran, and it works as expected. We should recommend a certain version of Go (> 1.3) in the MemGator requirements, @ibnesayeed .
