### ISSUE TITLE
Hosting a MemGator instance on FOSSHOST

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/MemGator#134]
Contact [FOSSHOST](https://fosshost.org/) to see if they will be willing to support an instance if MemGator for public use.

**Comment by machawk1** [comment]
FOSSHOST appears to have shutdown per [this Dec. 2022 HN post](https://news.ycombinator.com/item?id=33848529).

**Comment by phonedude** [comment]
If you wait long enough, the issues close themselves ;-(

**Comment by machawk1** [comment]
@phonedude Sadly, yes. PRs welcome. ;-)

**Comment by phonedude** [comment]
ahem.  https://github.com/oduwsdl/MemGator/commit/aa956b6a4ae8bacda4d935caba906c3fbfc2ab6e

**Comment by machawk1** [comment]
@phonedude ![mln](https://github.com/oduwsdl/MemGator/assets/2514780/0ac287b4-00e1-4285-b6d5-619048c8e4e1)
