### ISSUE TITLE
Add Israeli web archive

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/MemGator#139]
Once the service is stable, we may want to add it to known archives' list so that results from there are aggregated by default. Currently, the service is not easily discoverable, running on port `8080` publicly, which means no TLS certs in place.

```
TimeMap: http://wayback.nli.org.il:8080/timemap/link/
TimeGate: http://wayback.nli.org.il:8080/
```

**Comment by machawk1** [comment]
@ibnesayeed How did you come to know of this web archive?

**Comment by ibnesayeed** [comment]
@phonedude shared this in an email.

**Comment by machawk1** [comment]
It appears that any requests to the port 8080 endpoint now direct to https endpoints

```
TimeMap: https://wayback.nli.org.il/timemap/link/
TimeGate: https://wayback.nli.org.il/
```

Sample memento at https://wayback.nli.org.il/20160308230541/http://www.timesofisrael.com/
