### ISSUE TITLE
Unclear if custom archives.json is being used

### ISSUE THREAD

**Issue by ikreymer** [oduwsdl/memgator#17]
I'm specifying a custom archives.json with `--arc=/archives.json` but it appears that archives that are set to ignore are still being queried. Also, using an invalid file for the `--arc=` param does not generate an error, so perhaps it is not being recognized?
It would be useful to show the archives.json file being used in the initial start-up message, along with the endpoints.

Here is a version of Netcapsule using Memgator: https://github.com/ikreymer/netcapsule/tree/with-memgator

It is working pretty well general (was able to drop-in replace the LANL aggregator w/o any changes), though had to bump the timeouts also, as it seems most apis timeout...

**Comment by ibnesayeed** [comment]
I have tested it locally and does read the archive file. Also, it reports error when the file is missing or the path is wrong. I think I found what was the issue in your compose file and have fixed it. You can see another [pull request](https://github.com/ikreymer/netcapsule/pull/2). You were using `server` keyword argument as a sub-command (that is equivalent to the URI-R in CLI mode as far as argument processing is concerned), as a result all the flags after the `server` keyword were ignored. Please accept the PR and run that again to see if it works.

**Comment by ikreymer** [comment]
ok, thanks yes, that does fix it, and I saw that there was a typo in my archives.json file.
It would still be useful to add a printout of "Using archives.json from ..." on startup just for confirmation, but otherwise I think this is settled.

**Comment by ibnesayeed** [comment]
> It would still be useful to add a printout of "Using archives.json from ..." on startup just for confirmation

Makes sense to me. I will probably add it in verbose mode which will be consistent in both service and CLI. In my opinion it does not belong to the same place where endpoints are listed because that only appears in server mode and suggests users what to do next.
