### ISSUE TITLE
Aggregator should support 200-style negotiation from TimeGate

### ISSUE THREAD

**Issue by ikreymer** [oduwsdl/memgator#40]
Aggregator should support 200-style negotiation: https://tools.ietf.org/html/rfc7089#section-4.2.2

Looking at the info, current result is:
```
INFO: 2015/11/04 03:29:59.563596 rhiz => Response error: 200 OK (expected: 302)
```

(pywb supports this style of replay in order to minimize HTTP roundtrips caused by redirects and preserve the accept-datetime in the timestamp)

I think this should just be a matter of looking for `Content-Location` header instead of `Location` if status code is 200.

**Comment by ibnesayeed** [comment]
Makes sense to me. I will look the specs for this alternative negotiation option.

**Comment by ikreymer** [comment]
FYI, linked is my solution for now so that I can keep using memgator with this, not necessarily the right solution, though can do pull request if you'd like

**Comment by ibnesayeed** [comment]
Awesome! I am glad that you could help yourself despite poorly named variables with zero comments. I will tweak that piece differently in next commit. I will get rid of the `expst` variable which was there to pick one of the two status codes based on the branch (TimeMap or TimeGate). Now I can directly put the two status codes (in fact the constants provided by the http library) there in the conditional.

**Comment by ibnesayeed** [comment]
@ikreymer please feel free to build from the latest code (or download the ibnesayeed/memgator:master docker image) and see if it works now. In case you find something breaking, please reopen this issue.
