### ISSUE TITLE
Provide a streaming Pub/Sub endpoint for statistics

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/memgator#44]
It will be nice to expose the CDXJ formatted profiling data on an endpoint to allow clients to subscribe to it and create visualizations from it.

**Comment by machawk1** [comment]
:+1:

**Comment by ibnesayeed** [comment]
This, when implemented, will enable generation of live timeline plots of the service health and analytics ([sample](https://jsfiddle.net/qfv57m7m/1/)), visuals inspired by [this](http://www.bitlisten.com/) and many more.

**Comment by machawk1** [comment]
Is the intention for this to be the endpoint at port 80? I realize that the port number is arbitrary but it seems like the most intuitive choice for the user to test for an endpoint when deployed. On the contrary, it is probably the most likely to have a conflict, so echo'ing out the endpoint's address (+port) on launch would probably be better. If the user wishes to be reminded of all of the endpoints for the service, however, how do you imagine you will report this information?

**Comment by ibnesayeed** [comment]
This won't be a sub-service (hence no need for a separate port number), instead the stream will be available under a specific path endpoint such as `/stats`. There will be a boolean config flag to turn this on/off though.

As far as the advertisement of endpoints is concerned, when it is started in the server mode, it outputs available endpoint on the terminal. That same is also provided as payload when a GET request is made to the root of the service.

**Comment by machawk1** [comment]
👍  

Would also like to see a sample usage demo for the README/wiki.
