### ISSUE TITLE
memgator may generate invalid JSON for timemap response

### ISSUE THREAD

**Issue by ikreymer** [oduwsdl/memgator#48]
I noticed this as part of the response for timemap for `http://eff.org/` using the standard archives:

```
      {
        "datetime": "2011-12-07T20:51:07Z",
        "uri": "http://webarchive.loc.gov/all/20111207205107/https://www.eff.org/%!"(MISSING)
      },
```

Looking at the timemap from `webarchive.loc.goc`, it looks like it returns:

```
<http://webarchive.loc.gov/all/20111207205107/https://www.eff.org/%20>; rel="memento"; datetime="Wed, 07 Dec 2011 20:51:07 GMT",
```

so the MISSING thing is being added by memgator somehow..

**Comment by ibnesayeed** [comment]
Explaination: The string was being serialized correctly, but at the time of writing it to the response writer object it was being interpolated again and the `fmt` package tried to replace `%20` with an operand that was not present.

TODO: I need to globally update the script to use formatting functions such as `Print`, `Println`, `Printf`, `Fprint`, `Fprintf`, `Fprintln` etc. in a coherent manner.

**Comment by ikreymer** [comment]
Great, thanks for the quick fix!
