### ISSUE TITLE
Document the tolerance, dormant, and user-agent flags in the README

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/memgator#66]
Introduced in #43 and #62 (resp)

I assume that you were planning to add this for the next RC, @ibnesayeed , but it would be useful to have it in the README so users don't have to refer to the ticket nor be completely unaware that this functionality exists.

**Comment by ibnesayeed** [comment]
It is definitely something that will go in the README. We have introduced three new flags, so the help output needs to be updated accordingly. I was delaying it until we are ready for a new RC, so that other changes can be documented as well.
