### ISSUE TITLE
Change the default contact in the user-agent

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/memgator#90]
Currently, the default contact in the user-agent is listed as <@WebSciDL>. As a result, upstream servers often think the requests are coming from WSDL research group. We need to change the default to something else.

**Comment by machawk1** [comment]
@ibnesayeed I presume a placeholder would work best here, correct? Maybe "@Administrator", "MEMGATOR_ADMIN", "CHANGE_ME", or something of the like?

**Comment by ibnesayeed** [comment]
I am thinking of changing it to `<@WebSciDL (Default)>`. It has been really helpful to keep `@WebSciDL` there as we were approached (and came to know about) when service providers faced some issues from MemGator instances that we don't control.

To make it more obvious, we can perhaps print a warning when MemGator is run in the server mode without custom contact or user agent (or spoof flag).

**Comment by machawk1** [comment]
What might be better is to simply keep @WebSciDL sans (default), check the condition of that exact string and only then print a warning.

**Comment by ibnesayeed** [comment]
That would work too. So we basically only need to add that warning mechanism and that's all.
